name: Publish on crates.io

on:
  workflow_dispatch:

jobs:
  publish-rust:
    runs-on: ubuntu-latest
    environment: crates.io
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v7
      - uses: rust-lang/crates-io-auth-action@v1
        id: auth
      - run: cargo publish -p leptos_ext
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
